name: Deploy Batch Job

on:
  push:
    branches: [main]
    paths:
      - "cloud_run_job/**"
      - "scraper/**"
      - "great_expectations/**"
      - "dbt/**"
  workflow_dispatch: {}

env:
  GCP_PROJECT_ID: silesia-housing-data-platform
  GCP_REGION: europe-central2
  AR_REPO: housing-batch-job
  IMAGE_NAME: daily-batch
  RUN_JOB_NAME: housing-daily-batch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: housing-ci-deploy-sa@silesia-housing-data-platform.iam.gserviceaccount.com

      - uses: google-github-actions/setup-gcloud@v2
      # rest unchanged